name: FunnyGuilds
main: net.dzikoysk.funnyguilds.server.spigot.FunnyGuildsSpigotPlugin
version: '5.0.0'
author: 'FunnyGuilds Team'
website: https://github.com/FunnyGuilds
softdepend: [WorldEdit, WorldGuard, Vault, PlaceholderAPI, FunnyTab, HolographicDisplays, DecentHolograms, Multiverse-Core]
api-version: 1.16