language: java
sudo: required
dist: trusty

install: script/install
script: script/script

matrix:
  fast_finish: false
  include:
    - jdk: openjdk8
    - jdk: openjdk12

notifications:
  email: false
